In [9]:
import numpy as np
import torch

In [8]:
import sys
sys.path.append('/home/er647/projects/feature-wise-active-learning/src')

from models import FWAL

# Now you can use FWAL class


In [18]:
torch.bernoulli(torch.Tensor([0.1,0.5,0.9]))

tensor([0., 0., 1.])

L1 regularizer = 0

In [19]:
# Assuming 'model.ckpt' is your checkpoint file
checkpoint_path = '/home/er647/projects/feature-wise-active-learning/fwal/i22brw5y/checkpoints/last.ckpt'
args={
    'lr':None,
    'num_features':5,
    'num_classes':2
    }

import argparse

args = argparse.Namespace(**args)

# Load the trained model from the checkpoint
trained_model = FWAL.load_from_checkpoint(checkpoint_path, args=args)

Namespace(lr=None, num_features=5, num_classes=2)

In [11]:
trained_model.mask

Parameter containing:
tensor([0.5188, 0.6100, 0.7584, 0.7036, 0.3879], device='cuda:0',
       requires_grad=True)

L1 regularizer = 1

In [2]:

checkpoint_path = '/home/er647/projects/feature-wise-active-learning/fwal/6zj4la83/checkpoints/last.ckpt'
args={
    'lr':None,
    'num_features':5,
    'num_classes':2
    }

import argparse

args = argparse.Namespace(**args)

# Load the trained model from the checkpoint
trained_model = FWAL.load_from_checkpoint(checkpoint_path, args=args)
trained_model.mask

Parameter containing:
tensor([ 4.8612e-04,  2.1689e-03,  5.3685e-03,  1.0980e-06, -3.3920e-04],
       device='cuda:0', requires_grad=True)

In [7]:
rounded_tensor = np.around(trained_model.mask.detach().cpu().numpy(), decimals=4)

# Print the rounded values
print(rounded_tensor)

[ 0.0005  0.0022  0.0054  0.     -0.0003]


Hoyer regularizer

In [8]:
checkpoint_path = '/home/er647/projects/feature-wise-active-learning/fwal/980m2bnj/checkpoints/last.ckpt'
args={
    'lr':None,
    'num_features':5,
    'num_classes':2
    }

import argparse

args = argparse.Namespace(**args)

# Load the trained model from the checkpoint
trained_model = FWAL.load_from_checkpoint(checkpoint_path, args=args)
trained_model.mask

Parameter containing:
tensor([ 3.0875e-04,  9.4777e-03,  1.6940e+00,  1.7864e-03, -3.2130e-04],
       device='cuda:0', requires_grad=True)

In [9]:
rounded_tensor = np.around(trained_model.mask.detach().cpu().numpy(), decimals=4)

# Print the rounded values
print(rounded_tensor)

[ 3.000e-04  9.500e-03  1.694e+00  1.800e-03 -3.000e-04]


Hoyer regularizer = 1; reconstruction gamma = 1 